#!/bin/sh
#
# Copyright 2018 Charlotte Koch <cfkoch@edgebsd.org>
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
# LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# =========================================================================
#
# timezone(1)
# Convenience wrapper around getting and setting the system-wide timezone 
#

set -e

PROGNAME=$(basename $0)

usage() {
  echo "${PROGNAME}: usage: ${PROGNAME} [command] [options]" 1>&2
  echo "    ${PROGNAME} get" 1>&2
  echo "    ${PROGNAME} list" 1>&2
  echo "    ${PROGNAME} set <timezone>" 1>&2
  echo "    ${PROGNAME} help" 1>&2
}

note() {
  echo "${PROGNAME}: $1" 1>&2
}

complain() {
  note "error: $1"
  exit 1
}

THE_SYMLINK=/etc/localtime
ZONE_DATABASE=/usr/share/zoneinfo

# In case specific systems need overrides:
case "$(uname -s)" in
*)
  # nothing special
  ;;
esac

COMMAND=get

if [ $# -gt 0 ]; then
  case "$1" in
  get)
    # nothing to do, the default is already "get"
    ;;
  help)
    usage
    exit 0
    ;;
  list)
    COMMAND=list
    shift
    ;;
  set)
    COMMAND=set
    shift
    ;;
  *)
    complain "unknown command \"$1\""
    ;;
  esac
fi

do_get() {
  readlink ${THE_SYMLINK} | sed s,${ZONE_DATABASE}/,,
}

do_list() {
  find ${ZONE_DATABASE} -type f | sed s,${ZONE_DATABASE}/,, | ${PAGER:-less}
}

do_set() {
  given_zone="$1"

  if [ -z "${given_zone}" ]; then
    complain "expected a zone"
  fi

  candidate="${ZONE_DATABASE}/${given_zone}"

  if [ ! -f "${candidate}" ]; then
    complain "no such timezone file \"${given_zone}\""
  fi

  if [ "${candidate}" = "$(do_get)" ]; then
    note "timezone is already set to \"${given_zone}\""
    return
  fi

  ln -sf "${candidate}" ${THE_SYMLINK}
}

case "${COMMAND}" in
get)
  do_get
  ;;
list)
  do_list
  ;;
set)
  do_set "$1"
esac
